// <auto-generated />
using System;
using CoreRanking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreRanking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201011022008_AccountTable")]
    partial class AccountTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreRanking.Model.Battle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("killedId")
                        .HasColumnType("int");

                    b.Property<int>("killerId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Battle");
                });

            modelBuilder.Entity("CoreRanking.Model.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Login")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CoreRanking.Model.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("characterClass")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("characterName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("evento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("lastIp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.HasKey("roleId");

                    b.HasIndex("AccountId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CoreRanking.Model.Role", b =>
                {
                    b.HasOne("CoreRanking.Model.Data.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
