// <auto-generated />
using System;
using CoreRanking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreRanking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210403223040_INITIAL")]
    partial class INITIAL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("CoreRanking.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvE.Collect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Collect");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvE.Hunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Hunt");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Banned", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BanTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Banned");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("KilledId")
                        .HasColumnType("int");

                    b.Property<int>("KillerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KilledId");

                    b.HasIndex("KillerId");

                    b.ToTable("Battle");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterClass")
                        .HasColumnType("longtext");

                    b.Property<string>("CharacterGender")
                        .HasColumnType("longtext");

                    b.Property<string>("CharacterName")
                        .HasColumnType("longtext");

                    b.Property<double>("CollectPoint")
                        .HasColumnType("double");

                    b.Property<int>("Doublekill")
                        .HasColumnType("int");

                    b.Property<string>("Elo")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Pentakill")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Quadrakill")
                        .HasColumnType("int");

                    b.Property<int>("Triplekill")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("AccountId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvE.Collect", b =>
                {
                    b.HasOne("CoreRanking.Model.RankingPvP.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvE.Hunt", b =>
                {
                    b.HasOne("CoreRanking.Model.RankingPvP.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Banned", b =>
                {
                    b.HasOne("CoreRanking.Model.RankingPvP.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Battle", b =>
                {
                    b.HasOne("CoreRanking.Model.RankingPvP.Role", "KilledRole")
                        .WithMany()
                        .HasForeignKey("KilledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreRanking.Model.RankingPvP.Role", "KillerRole")
                        .WithMany()
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KilledRole");

                    b.Navigation("KillerRole");
                });

            modelBuilder.Entity("CoreRanking.Model.RankingPvP.Role", b =>
                {
                    b.HasOne("CoreRanking.Model.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
