// <auto-generated />
using System;
using CoreRanking.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreRanking.Migrations.LicenseDb
{
    [DbContext(typeof(LicenseDbContext))]
    partial class LicenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreRanking.Model.CoreRankingLicense", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("hwid")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("licensekey")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("user")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("validade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("CoreRankingLicense");
                });
#pragma warning restore 612, 618
        }
    }
}
